uint8 type
geometry_msgs/Point[] lla_points
sensor_msgs/NavSatFix[] gps_points
---
float64 origin_latitude
float64 origin_longitude
geometry_msgs/Point[] res_lla_points
sensor_msgs/NavSatFix[] res_gps_points

uint8 TYPE_GPS2LLA = 0
uint8 TYPE_LLA2GPS = 1