uint8 mode
float32 target_x
float32 target_y
float32 longitude
float32 latitude
---
bool result
uint8 current_mode
geometry_msgs/Point[] traj
uint16 error_code
string error_msg

uint8 MODE_GPS   = 1
uint8 MODE_LIDAR = 2