uint8 command
---
bool result
uint8 current_status
uint16 error_code
string error_msg

uint8 COMMAND_RUN   = 1
uint8 COMMAND_PAUSE = 2
uint8 COMMAND_ABORT = 3

uint8 STATUS_RUN    = 1
uint8 STATUS_PAUSE  = 2
uint8 STATUS_STOP   = 3